events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. 抽獎系統
        location /lottery/ {
            proxy_pass https://lottery-609981588827.asia-east1.run.app/;
            proxy_set_header Host lottery-609981588827.asia-east1.run.app;
        }

        # 2. 名片系統
        location /id card/ {
            proxy_pass https://ochatsuki-id-name-609981588827.asia-east1.run.app/;
            proxy_set_header Host ochatsuki-id-name-609981588827.asia-east1.run.app;
        }

        # 3. 發貨系統
        location /order/ {
            proxy_pass https://ochatsuki-order-609981588827.asia-northeast1.run.app/;
            proxy_set_header Host ochatsuki-order-609981588827.asia-northeast1.run.app;
        }

        # 預設首頁 (如果只打 client.xxx.com.tw)
        location / {
            return 200 "這是 Client 總站";
            add_header Content-Type text/plain;
        }
    }
}